In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['seeds_dataset.csv']


# Wheat Seed Prediction

In [2]:
# Load libraries
import numpy
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import PowerTransformer

## Load Dataset

In [3]:
# Load dataset
filename = "../input/seeds_dataset.csv"
names = ["areaA", "perimeterP", "compactnessC", "lengthkernel", "widthkernel",
         "asymmetry", "lengthkernelgroove", "class"]
dataset = read_csv(filename, delim_whitespace=True, names=names)

## Prepare data

In [4]:
# Split-out validation dataset
array = dataset.values
X = array[:, 0:7]
Y = array[:, 7]
validation_size = 0.30
seed = 7

## Prepare Data for LDA using Box-Cox

In [5]:
# make data Gaussian-Like
bc = PowerTransformer(method="box-cox", standardize=True)
X_pt = bc.fit_transform(X)

In [6]:
X_train, X_validation, Y_train, Y_validation = \
    train_test_split(X_pt, Y, test_size=validation_size, random_state=seed)
num_folds = 10
seed = 7
scoring = 'accuracy'

## Predictions on validation dataset

In [7]:
# Predictions on validation dataset
# LinearDiscriminantAnalysis as model
model = LinearDiscriminantAnalysis()
model.fit(X_train, Y_train)

# estimate accuracy on validation dataset
predictions = model.predict(X_validation)

print("Accuracy score:")
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

Accuracy score:
1.0
[[20  0  0]
 [ 0 23  0]
 [ 0  0 20]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        20
         2.0       1.00      1.00      1.00        23
         3.0       1.00      1.00      1.00        20

   micro avg       1.00      1.00      1.00        63
   macro avg       1.00      1.00      1.00        63
weighted avg       1.00      1.00      1.00        63

